In [17]:
import numpy as np
import pandas as pd

In [18]:
import os
os.getcwd()

'/hkfs/work/workspace/scratch/bh6321-E6/infamous-werewolves'

In [19]:
DATA_DIR = "/hkfs/work/workspace/scratch/bh6321-energy_challenge/data/train.csv"
DATA_DIR_DANIEL = "./data/processed/"
TRAIN = "train.csv"
VAL = "valid.csv"

In [20]:
df = pd.read_csv(DATA_DIR_DANIEL+TRAIN)
#df.rename(columns={"Time [s]":"time", "Load [MWh]": "load", "City": "city"}, inplace=True)
#df["time"] = pd.to_datetime(df["time"])

In [21]:
CITIES = df.city.unique()

In [22]:
df.head()

load                 time city  hour  day_name  weekday  day  month  \
0  263.365956  2015-01-01 00:00:00   bs     0  Thursday        3    1      1   
1  259.073621  2015-01-01 01:00:00   bs     1  Thursday        3    1      1   
2  246.612481  2015-01-01 02:00:00   bs     2  Thursday        3    1      1   
3  238.313719  2015-01-01 03:00:00   bs     3  Thursday        3    1      1   
4  237.114390  2015-01-01 04:00:00   bs     4  Thursday        3    1      1   

   year  dayofyear  ...  month_cos  dayofyear_sin  dayofyear_cos   latitute  \
0  2015          1  ...   0.866025       0.017213       0.999852  52.266667   
1  2015          1  ...   0.866025       0.017213       0.999852  52.266667   
2  2015          1  ...   0.866025       0.017213       0.999852  52.266667   
3  2015          1  ...   0.866025       0.017213       0.999852  52.266667   
4  2015          1  ...   0.866025       0.017213       0.999852  52.266667   

   longitude  elevation  is_day  is_dusk  is_dawn  sun_position  
0  10.516667   76.70401       0        0        0    -59.840175  
1  10.516667   76.70401       0        0        0    -55.195090  
2  10.516667   76.70401       0        0        0    -47.964556  
3  10.516667   76.70401       0        0        0    -39.408925  
4  10.516667   76.70401       0        0        0    -30.318257  

[5 rows x 25 columns]

In [23]:
city_mapper = {'h': "Hannover", 
               'bs': "Braunschweig", 
               'ol': "Oldenburg", 
               'os': "Osnabrück", 
               'wob': "Wolfsburg", 
               'go': "Göttingen",
               'sz': "Salzgitter", 
               'hi': "Hildesheim", 
               'del': "Delmenhorst", 
               'lg': "Lüneburg", 
               'whv': "Wilhelmshaven", 
               'ce': "Celle", 
               'hm': "Hameln", 
               'el': "Lingen(Ems)"
              }

## Hourly Training

In [24]:
df_tmp_list = []
for city in CITIES:
    df_tmp = df.loc[df.city == city,:]
    df_tmp.loc[:,"y"] = df_tmp.loc[:,"load"].shift(-1)
    df_tmp.dropna(inplace=True)
    df_tmp_list.append(df_tmp)
df_y = pd.concat(df_tmp_list)
df_y.head()

/software/all/jupyter/tensorflow/2022-01-11/lib/python3.8/site-packages/pandas/core/indexing.py:1667: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
/software/all/jupyter/tensorflow/2022-01-11/lib/python3.8/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


load                 time city  hour  day_name  weekday  day  month  \
0  263.365956  2015-01-01 00:00:00   bs     0  Thursday        3    1      1   
1  259.073621  2015-01-01 01:00:00   bs     1  Thursday        3    1      1   
2  246.612481  2015-01-01 02:00:00   bs     2  Thursday        3    1      1   
3  238.313719  2015-01-01 03:00:00   bs     3  Thursday        3    1      1   
4  237.114390  2015-01-01 04:00:00   bs     4  Thursday        3    1      1   

   year  dayofyear  ...  dayofyear_sin  dayofyear_cos   latitute  longitude  \
0  2015          1  ...       0.017213       0.999852  52.266667  10.516667   
1  2015          1  ...       0.017213       0.999852  52.266667  10.516667   
2  2015          1  ...       0.017213       0.999852  52.266667  10.516667   
3  2015          1  ...       0.017213       0.999852  52.266667  10.516667   
4  2015          1  ...       0.017213       0.999852  52.266667  10.516667   

   elevation  is_day  is_dusk  is_dawn  sun_position           y  
0   76.70401       0        0        0    -59.840175  259.073621  
1   76.70401       0        0        0    -55.195090  246.612481  
2   76.70401       0        0        0    -47.964556  238.313719  
3   76.70401       0        0        0    -39.408925  237.114390  
4   76.70401       0        0        0    -30.318257  237.344602  

[5 rows x 26 columns]

df_y = pd.get_dummies(df_y, columns=["city",])

In [33]:
df = df_tmp_list[0]

In [34]:
df.rolling(12).mean()

load  hour  weekday   day  month    year  dayofyear  hour_sin  \
0             NaN   NaN      NaN   NaN    NaN     NaN        NaN       NaN   
1             NaN   NaN      NaN   NaN    NaN     NaN        NaN       NaN   
2             NaN   NaN      NaN   NaN    NaN     NaN        NaN       NaN   
3             NaN   NaN      NaN   NaN    NaN     NaN        NaN       NaN   
4             NaN   NaN      NaN   NaN    NaN     NaN        NaN       NaN   
...           ...   ...      ...   ...    ...     ...        ...       ...   
26298  203.806092  12.5      6.0  31.0   12.0  2017.0      365.0 -0.164729   
26299  205.568573  13.5      6.0  31.0   12.0  2017.0      365.0 -0.317242   
26300  206.225481  14.5      6.0  31.0   12.0  2017.0      365.0 -0.446225   
26301  206.990378  15.5      6.0  31.0   12.0  2017.0      365.0 -0.542115   
26302  208.199299  16.5      6.0  31.0   12.0  2017.0      365.0 -0.597798   

       hour_cos       day_sin  ...  dayofyear_sin  dayofyear_cos   latitute  \
0           NaN           NaN  ...            NaN            NaN        NaN   
1           NaN           NaN  ...            NaN            NaN        NaN   
2           NaN           NaN  ...            NaN            NaN        NaN   
3           NaN           NaN  ...            NaN            NaN        NaN   
4           NaN           NaN  ...            NaN            NaN        NaN   
...         ...           ...  ...            ...            ...        ...   
26298 -0.587927 -2.449294e-16  ...   6.432491e-16            1.0  52.266667   
26299 -0.521682 -2.449294e-16  ...   6.432491e-16            1.0  52.266667   
26300 -0.416745 -2.449294e-16  ...   6.432491e-16            1.0  52.266667   
26301 -0.280901 -2.449294e-16  ...   6.432491e-16            1.0  52.266667   
26302 -0.124224 -2.449294e-16  ...   6.432491e-16            1.0  52.266667   

       longitude  elevation    is_day   is_dusk   is_dawn  sun_position  \
0            NaN        NaN       NaN       NaN       NaN           NaN   
1            NaN        NaN       NaN       NaN       NaN           NaN   
2            NaN        NaN       NaN       NaN       NaN           NaN   
3            NaN        NaN       NaN       NaN       NaN           NaN   
4            NaN        NaN       NaN       NaN       NaN           NaN   
...          ...        ...       ...       ...       ...           ...   
26298  10.516667   76.70401  0.750000  0.166667  0.166667      2.121865   
26299  10.516667   76.70401  0.666667  0.166667  0.083333     -0.398752   
26300  10.516667   76.70401  0.583333  0.166667  0.000000     -4.158105   
26301  10.516667   76.70401  0.500000  0.166667  0.000000     -9.074033   
26302  10.516667   76.70401  0.416667  0.166667  0.000000    -14.871472   

                y  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             NaN  
...           ...  
26298  205.568573  
26299  206.225481  
26300  206.990378  
26301  208.199299  
26302  208.482113  

[26303 rows x 23 columns]

In [25]:
FEATURES = list(df_y.columns)
FEATURES.remove("y")
FEATURES.remove("day_name")
FEATURES.remove("city")
FEATURES.remove("time")

In [26]:
df_y.dtypes

load             float64
time              object
city              object
hour               int64
day_name          object
weekday            int64
day                int64
month              int64
year               int64
dayofyear          int64
hour_sin         float64
hour_cos         float64
day_sin          float64
day_cos          float64
month_sin        float64
month_cos        float64
dayofyear_sin    float64
dayofyear_cos    float64
latitute         float64
longitude        float64
elevation        float64
is_day             int64
is_dusk            int64
is_dawn            int64
sun_position     float64
y                float64
dtype: object

In [27]:
df_tmp_list[0].shape

(26303, 26)

In [28]:
from sklearn.ensemble import RandomForestRegressor

In [30]:
regressors = {}

for df_tmp in df_tmp_list:
    
    city = df_tmp.city.unique()[0]
    
    print("City: ", city)
    
    X = df_tmp[FEATURES]
    y = df_tmp["y"]
    
    regr = RandomForestRegressor(n_estimators=2000,
                                 max_depth=20, 
                                 criterion="squared_error",
                                 max_features="sqrt",
                                 random_state=7531,
                                 oob_score=False,
                                 n_jobs=-1)
    
    regr.fit(X,y)
    
    regressors[city] = regr

print("DONE")

City:  bs
City:  h
City:  hm
City:  ol
City:  del
City:  el
City:  os
City:  wob
City:  hi
City:  whv
City:  lg
City:  ce
City:  go
City:  sz


In [ ]:
def predict_loop(model, X, horizon=7*24):
    predictions = []
    
    for h in range(horizon):
        pred = model.predict(X)
        predictions.append(pred)
        
        X["load"] = pred
    
    return predictions

In [32]:
np.zeros(168).shape

(168,)

In [64]:
n = 200000
X = df_y[FEATURES][:n]
y = df_y["y"][:n]

In [27]:
from sklearn.datasets import make_regression
X,y = make_regression(n_samples=50000, n_features=20, n_informative=10)

In [28]:
import multiprocessing
multiprocessing.cpu_count()

152

In [30]:
import gc
gc.collect()

3665

In [19]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [35]:
import xgboost as xgb
from xgboost import XGBRegressor

xgbr = XGBRegressor(objective='reg:squarederror')
#xgb.fit(X_train, y_train)

pipe_xgb = make_pipeline(StandardScaler(), xgbr)

# with open("results/demand_xgboost_hyperopt_2021-02-24T01-19-23.json", "r") as f:
#     params = json.load(f)
params_1 = {"xgbregressor__colsample_bytree": 0.022073333648539202, 
            "xgbregressor__learning_rate": 0.06012540666679903, 
            "xgbregressor__max_depth": 4, 
            "xgbregressor__min_child_weight": 6.337892352836798, 
            "xgbregressor__n_estimators": 10946, 
            "xgbregressor__reg_lambda": 1.3566888572323035, 
            "xgbregressor__subsample": 0.8941866568313804}

params_2 = {'xgbregressor__colsample_bytree': 0.0867, 
            'xgbregressor__learning_rate': 0.0845651857308635, 
            'xgbregressor__max_depth': 21, 
            'xgbregressor__min_child_weight': 15.0, 
            'xgbregressor__n_estimators': 9779, 
            'xgbregressor__reg_lambda': 2.1318018187083574, 
            'xgbregressor__subsample': 0.91}

params_3 = {'colsample_bytree': 0.049, 
             'learning_rate': 0.0113, 
             'max_depth': 9, 
             'min_child_weight': 31., 
             'n_estimators': 5000, 
             'reg_lambda': 2., 
             'subsample': 0.8}

xgbr.set_params(**params_3)

XGBRegressor(base_score=None, booster=None, colsample_bylevel=None,
             colsample_bynode=None, colsample_bytree=0.049,
             enable_categorical=False, gamma=None, gpu_id=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.0113, max_delta_step=None, max_depth=9,
             min_child_weight=31.0, missing=nan, monotone_constraints=None,
             n_estimators=5000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, reg_alpha=None, reg_lambda=2.0,
             scale_pos_weight=None, subsample=0.8, tree_method=None,
             validate_parameters=None, verbosity=None)

In [36]:
xgbr.fit(X, y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.049,
             enable_categorical=False, gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.0113, max_delta_step=0,
             max_depth=9, min_child_weight=31.0, missing=nan,
             monotone_constraints='()', n_estimators=5000, n_jobs=76,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=2.0, scale_pos_weight=1, subsample=0.8,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [42]:
regr = RandomForestRegressor(n_estimators=1000,
                             max_depth=5, 
                             criterion="mse",
                             max_features="sqrt",
                             random_state=7531,
                             oob_score=False,
                             n_jobs=-1)

In [43]:
regr.fit(X,y)

/hkfs/home/project/haicore-project-ai-hero/ng3223/env_aihero/lib64/python3.8/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


RandomForestRegressor(criterion='mse', max_depth=5, max_features='sqrt',
                      n_estimators=1000, n_jobs=-1, random_state=7531)

In [40]:
%time regr.fit(X, y)

/hkfs/home/project/haicore-project-ai-hero/ng3223/env_aihero/lib64/python3.8/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


CPU times: user 1min 29s, sys: 306 ms, total: 1min 29s
Wall time: 1.96 s


RandomForestRegressor(criterion='mse', max_depth=5, max_features='sqrt',
                      n_estimators=1000, n_jobs=-1, random_state=7531)

In [24]:
from sklearn.svm import SVR


regr = make_pipeline(StandardScaler(), SVR(C=1.0, epsilon=0.2, kernel="rbf"))
regr.fit(X, y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svr', SVR(epsilon=0.2))])

In [44]:
regr.score(X,y)

0.9765863513754692

In [72]:
df_val = pd.read_csv(DATA_DIR_DANIEL+VAL)

df_tmp_list_val = []
for city in CITIES:
    df_tmp = df.loc[df.city == city,:]
    df_tmp.loc[:,"y"] = df_tmp.loc[:,"load"].shift(-1)
    df_tmp.dropna(inplace=True)
    df_tmp_list.append(df_tmp)
df_val = pd.concat(df_tmp_list)
df_val.head()

/software/all/jupyter/base/2022-01-11/lib/python3.8/site-packages/pandas/core/indexing.py:1667: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
/software/all/jupyter/base/2022-01-11/lib/python3.8/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


load                 time city  hour  day_name  weekday  day  month  \
0  263.365956  2015-01-01 00:00:00   bs     0  Thursday        3    1      1   
1  259.073621  2015-01-01 01:00:00   bs     1  Thursday        3    1      1   
2  246.612481  2015-01-01 02:00:00   bs     2  Thursday        3    1      1   
3  238.313719  2015-01-01 03:00:00   bs     3  Thursday        3    1      1   
4  237.114390  2015-01-01 04:00:00   bs     4  Thursday        3    1      1   

   year  dayofyear  ...  dayofyear_sin  dayofyear_cos   latitute  longitude  \
0  2015          1  ...       0.017213       0.999852  52.266667  10.516667   
1  2015          1  ...       0.017213       0.999852  52.266667  10.516667   
2  2015          1  ...       0.017213       0.999852  52.266667  10.516667   
3  2015          1  ...       0.017213       0.999852  52.266667  10.516667   
4  2015          1  ...       0.017213       0.999852  52.266667  10.516667   

   elevation  is_day  is_dusk  is_dawn  sun_position           y  
0   76.70401       0        0        0    -59.840175  259.073621  
1   76.70401       0        0        0    -55.195090  246.612481  
2   76.70401       0        0        0    -47.964556  238.313719  
3   76.70401       0        0        0    -39.408925  237.114390  
4   76.70401       0        0        0    -30.318257  237.344602  

[5 rows x 26 columns]

df_val = pd.get_dummies(df_val, columns=["city"])

In [73]:
def mae(y_pred, y_true):
    return np.mean(np.abs(y_pred - y_true))

In [75]:
val_scores = []
for city in CITIES:
    df_tmp = df_val.loc[df_val.city == city,:]
    pred = regressors[city].predict(df_tmp[FEATURES])
    score = mae(pred, df_tmp["y"])
    val_scores.append(score)

In [76]:
val_scores

[0.8235501245564918,
 2.510048163112978,
 0.5679978393766416,
 1.0438099922160105,
 0.5241396178241883,
 0.283796031454187,
 0.41767956393804184,
 0.26442611257834925,
 0.2137775272122954,
 0.4050763720655824,
 1.2526940534032127,
 0.21083522427403323,
 1.1881662764651946,
 1.2591337215405491]

In [46]:
regr.score(df_val[FEATURES], df_val["y"])

0.7760010209452057

In [47]:
predictions = regr.predict(df_val[FEATURES])

In [57]:
regr.predict(df_val.iloc[-2:][FEATURES])

array([205.24076547, 204.50077992])

In [58]:
predictions

array([217.46860907, 217.60309997, 217.19935163, ..., 206.6413334 ,
       205.24076547, 204.50077992])

In [59]:
df_val["y"]

0         259.073621
1         246.612481
2         238.313719
3         237.114390
4         237.344602
             ...    
368250    322.822588
368251    312.235274
368252    317.510833
368253    325.311059
368254    309.321500
Name: y, Length: 368242, dtype: float64

In [48]:
np.mean(np.abs(predictions - df_val["y"].values))

61.16074988091494

In [10]:
df_cities = df.pivot_table(values='load', index=df.time, aggfunc='first', columns='city')

In [98]:
df_cities["bs"].shift(-24*7).fillna(0)

time
2015-01-01 00:00:00    244.871041
2015-01-01 01:00:00    240.147987
2015-01-01 02:00:00    228.544572
2015-01-01 03:00:00    224.794348
2015-01-01 04:00:00    233.304757
                          ...    
2017-12-31 19:00:00      0.000000
2017-12-31 20:00:00      0.000000
2017-12-31 21:00:00      0.000000
2017-12-31 22:00:00      0.000000
2017-12-31 23:00:00      0.000000
Name: bs, Length: 26304, dtype: float64

In [120]:
for city in df.city.unique():
    df_cities[city+"_y"] = df_cities[city].shift(24*7)

In [121]:
df_cities.dropna(inplace=True)

In [122]:
24*7

168

In [123]:
df_cities[["bs", "bs_y"]].iloc[:168]

city                         bs        bs_y
time                                       
2015-01-08 00:00:00  244.871041  263.365956
2015-01-08 01:00:00  240.147987  259.073621
2015-01-08 02:00:00  228.544572  246.612481
2015-01-08 03:00:00  224.794348  238.313719
2015-01-08 04:00:00  233.304757  237.114390
...                         ...         ...
2015-01-14 19:00:00  261.145526  280.034029
2015-01-14 20:00:00  245.283194  265.434149
2015-01-14 21:00:00  244.095004  263.380808
2015-01-14 22:00:00  247.117462  264.747226
2015-01-14 23:00:00  236.735655  253.871578

[168 rows x 2 columns]

In [124]:
def mae(y_true, y_pred):
    
    absolute_difference = np.abs(y_true - y_pred)
    
    return np.mean(absolute_difference)

In [125]:
df_cities.shape[0] // 168

155

In [126]:
mae_list = []
for i in range(df_cities.shape[0] // 168):
    mae_week = mae(df_cities["bs_y"].iloc[168*i:168*(i+1)].values, df_cities["bs"].iloc[168*i:168*(i+1)].values)
    mae_list.append(mae_week)

In [127]:
df_cities["bs"].iloc[168*(i-1):168*i].values

array([238.06122875, 233.59066508, 223.17172681, 220.16040859,
       229.85900686, 252.42347152, 275.43350731, 281.54154489,
       280.78036087, 279.62558902, 279.83723531, 279.8409484 ,
       275.95705339, 271.41594095, 266.18419326, 265.81659708,
       278.01781986, 288.18055473, 286.82527587, 271.94691321,
       256.67867581, 254.75529377, 257.89285714, 247.21028929,
       237.1143901 , 230.90981211, 221.57881002, 219.15787355,
       229.09410975, 252.28608709, 275.82338205, 283.13817477,
       282.36213838, 280.00432449, 280.16398747, 279.23200119,
       273.88514763, 267.59516851, 262.24460185, 262.42654339,
       277.3308977 , 285.95641217, 284.54543692, 270.91096033,
       258.79513868, 260.98586341, 264.93659409, 251.75511482,
       240.26680585, 234.06594095, 222.85982702, 217.84343871,
       221.49712198, 229.64736057, 240.13313451, 249.94312556,
       257.52897405, 259.0921861 , 259.45978228, 263.2954071 ,
       256.50787355, 247.59645094, 240.98714584, 241.49

In [128]:
df_cities["bs"].iloc[168*i:168*(i+1)].values

array([241.83001789, 236.21953475, 225.86743215, 221.75332538,
       229.62508202, 251.13874143, 273.10911124, 280.55386221,
       278.9720847 , 277.50912616, 277.39402028, 276.71081121,
       271.47535043, 265.96512079, 260.44746496, 259.13303012,
       270.49138085, 279.53276171, 277.21207874, 262.63818968,
       249.41586639, 248.01603042, 250.88996421, 238.78899493,
       228.61512079, 222.36227259, 212.29979123, 208.46787951,
       216.32107068, 237.74190277, 258.74686848, 266.01339099,
       265.02570832, 263.46620936, 262.85354906, 262.71616463,
       257.5029824 , 251.05334029, 244.2880853 , 242.18276171,
       253.22549955, 260.43261259, 257.87057859, 246.05551745,
       234.73429764, 236.31236206, 238.751864  , 226.21646287,
       214.37912317, 206.89352818, 195.63914405, 190.65988667,
       193.15137191, 199.66784969, 208.56070683, 217.53525201,
       224.99114226, 228.05444378, 229.77360573, 235.74054578,
       231.12888458, 223.15316135, 217.3867283 , 215.79

In [151]:
np.average([df_cities["bs"].iloc[168*(i-1):168*i].values, df_cities["bs"].iloc[168*i:168*(i+1)].values], axis=0, weights=[.5,.5])

array([239.94562332, 234.90509991, 224.51957948, 220.95686698,
       229.74204444, 251.78110647, 274.27130928, 281.04770355,
       279.87622279, 278.56735759, 278.6156278 , 278.27587981,
       273.71620191, 268.69053087, 263.31582911, 262.4748136 ,
       274.25460036, 283.85665822, 282.0186773 , 267.29255145,
       253.0472711 , 251.38566209, 254.39141068, 242.99964211,
       232.86475544, 226.63604235, 216.93930063, 213.81287653,
       222.70759022, 245.01399493, 267.28512526, 274.57578288,
       273.69392335, 271.73526693, 271.50876827, 270.97408291,
       265.69406502, 259.3242544 , 253.26634357, 252.30465255,
       265.27819863, 273.19451238, 271.20800775, 258.48323889,
       246.76471816, 248.64911273, 251.84422905, 238.98578885,
       227.32296451, 220.47973457, 209.24948554, 204.25166269,
       207.32424694, 214.65760513, 224.34692067, 233.73918879,
       241.26005816, 243.57331494, 244.61669401, 249.51797644,
       243.81837906, 235.37480614, 229.18693707, 228.64

In [130]:
df_cities[city].iloc[168*0:168*(0+1)].values

array([380.75419821, 364.95466806, 354.83790133, 355.72470199,
       370.54694162, 408.19977378, 445.17393196, 460.80153137,
       465.2807796 , 467.85974071, 473.71443487, 461.75167493,
       465.75132689, 464.19490124, 462.32176107, 464.32158705,
       484.30174889, 482.33811885, 459.34464457, 437.09318716,
       419.20334116, 425.80005221, 420.18063169, 396.11937701,
       376.18446011, 363.43443835, 357.25398068, 352.92856521,
       369.41581832, 406.20899678, 438.21526146, 459.04602802,
       460.58435569, 461.73357696, 467.38919342, 456.35847907,
       452.6302967 , 444.45906204, 440.46845906, 447.0018272 ,
       462.43034891, 459.7880449 , 439.15635604, 413.58392065,
       394.81632298, 402.05551205, 401.91977726, 379.98503437,
       356.03236753, 337.46384756, 328.85826155, 317.48368572,
       321.98103193, 329.32880884, 343.49047246, 368.33898895,
       386.73557818, 401.21395632, 406.57095623, 408.74271296,
       400.6348212 , 393.15130949, 393.52231793, 394.07

In [131]:
df_cities[city+"_y"].iloc[168*0:168*(0+1)].values

array([345.74367006, 331.25624293, 318.47002523, 310.09066388,
       307.21308623, 305.07752545, 294.00156617, 296.05568607,
       301.85608631, 314.09031584, 322.09866875, 329.10258418,
       328.94875141, 323.60080049, 322.84973462, 326.36979031,
       349.80666493, 358.85565127, 356.61150265, 346.5128339 ,
       341.02914818, 358.20412425, 364.19455321, 343.4633255 ,
       325.81780214, 310.24449665, 301.18646132, 299.58479074,
       308.27181763, 325.75445924, 333.96188985, 353.58914122,
       370.77316628, 382.10249717, 390.21943792, 389.83033151,
       383.88514748, 373.5421561 , 370.12163926, 376.23875402,
       405.81989037, 413.6834595 , 400.20951884, 380.63656139,
       361.71513095, 375.08048377, 377.88566954, 357.63403811,
       336.43226312, 322.17106065, 309.49343078, 308.9504916 ,
       311.99095101, 322.92212651, 326.11641869, 347.68015314,
       366.20342817, 387.47759506, 400.61672322, 402.78847994,
       398.30923171, 391.47724702, 392.13782302, 400.77

In [194]:
def get_predictions(data, mean_window=1):
    results = {}
    
    if mean_window == 1:
    
        for city in CITIES:
            mae_list = []
            for i in range(df_cities.shape[0] // 168):
                prediction = df_cities[city].iloc[168*i:168*(i+1)].values
                true_y = df_cities[city+"_y"].iloc[168*i:168*(i+1)].values
                mae_week = mae(true_y, prediction)
                mae_list.append(mae_week)
            results[city] = np.mean(mae_list)
            
    elif mean_window == 2:
    
        for city in CITIES:
            mae_list = []
            for i in range(df_cities.shape[0] // 168):
                if i > 1:
                    prediction = np.average([df_cities[city].iloc[168*(i-1):168*i].values, df_cities[city].iloc[168*i:168*(i+1)].values], axis=0, weights=[.15,.85])
                else:
                    prediction = df_cities[city].iloc[168*i:168*(i+1)].values
                true_y = df_cities[city+"_y"].iloc[168*i:168*(i+1)].values
                mae_week = mae(true_y, prediction)
                mae_list.append(mae_week)
            results[city] = np.mean(mae_list)
            
    elif mean_window == 3:
    
        for city in CITIES:
            mae_list = []
            for i in range(df_cities.shape[0] // 168):
                if i > 2:
                    prediction = np.average([df_cities[city].iloc[168*(i-2):168*(i-1)].values, df_cities[city].iloc[168*(i-1):168*i].values, df_cities[city].iloc[168*i:168*(i+1)].values], axis=0, weights=[.05,.15,.8])
                elif i == 1:
                    prediction = np.average([df_cities[city].iloc[168*(i-1):168*i].values, df_cities[city].iloc[168*i:168*(i+1)].values], axis=0, weights=[.15,.85])
                else:
                    prediction = df_cities[city].iloc[168*i:168*(i+1)].values
                true_y = df_cities[city+"_y"].iloc[168*i:168*(i+1)].values
                mae_week = mae(true_y, prediction)
                mae_list.append(mae_week)
            results[city] = np.mean(mae_list)
        
    return results

In [195]:
results = get_predictions(df_cities, mean_window=3)

In [196]:
np.mean(list(results.values()))

7.357463477000352